' Preview durch <Alt>d

@startuml Controller-Klasse

interface Promise<T>

package @nestjs/common {
  class "@Controller" as Controller
  hide Controller circle

  class "@UseGuards" as UseGuards
  hide UseGuards circle

  class "@UseInterceptors" as UseInterceptors
  hide UseInterceptors circle

  class "@Post" as Post
  hide Post circle

  class "@Put" as Put
  hide Put circle

  class "@Delete" as Delete
  hide Delete circle

  class "@Req" as Req
  hide Req circle

  class "@Res" as Res
  hide Res circle

  class "@Param" as Param
  hide Param circle

  class "@Body" as Body
  hide Body circle

  class "@Headers" as Headers
  hide Headers circle

  UseInterceptors .[hidden].> Post
  UseInterceptors .[hidden].> Put
  UseInterceptors .[hidden].> Delete

  Post .[hidden].> Req
  Post .[hidden].> Res
  Post .[hidden].> Param
  Post .[hidden].> Body
  Post .[hidden].> Headers
}

package nest-keycloak-connect {
  class AuthGuard

  class "@Roles" as Roles
  hide Roles circle
}

package express {
  class Request
  class Response

  Response .right[hidden].> Controller
}

package auto {
  package entity #FFFFFF {
    class Auto <<entity>>

    Auto .[hidden].> Promise
    Auto .[hidden].> Request
  }

  package service {
    class AutoWriteService << control >>
    class AutoReadService << control >>
  }

  package rest #DDDDDD {
    class AutoWriteController << control >> << @Controller() >> << @UseGuards() >> << @UseInterceptors() >> {
      + @Post() @Roles() async post(@Body() auto: Auto, @Req() req: Request,  @Res() res: Response): Promise<Response>
      + @Put() @Roles() async put(@Body() auto: Auto, @Param() id: number, @Headers() version: string, @Res() res: Response): Promise<Response>
      + @Delete() @Roles() async delete(@Param() id: number, @Res() res: Response): Promise<Response>
    }

    AutoWriteController o--> "1" AutoWriteService : service
    AutoWriteController o--> "1" AutoReadService : readService
    AutoWriteController ..up> Auto

    AutoWriteController ..> Controller

    AutoWriteController .up.> AuthGuard
    AutoWriteController .up.> Roles

    AutoWriteController ..> Request
    AutoWriteController ..> Response
    AutoWriteController ..> Promise

    Auto .up[hidden].> Roles
    AutoWriteService .[hidden].> Request
    AutoWriteService .[hidden].> Promise
  }
}

hide empty members

@enduml
