' Preview durch <Alt>d

@startuml Komponenten

left to right direction

actor RESTClient
actor GraphQLClient

node "Nest" {
  [RequestLoggerMiddleware]

  [AutoController]
  [AutoResolver]

  [AutoService]

  [Repository<Auto>]

  [MailService]
}


cloud {
    [TypeORM]
}

cloud {
    [nest-keycloak-connect]
}

cloud {
    [nodemailer]
}

database "DB auto" {
    [Tabelle auto]
    [Tabelle modell]
    [Tabelle bild]
}

node {
    [Keycloak]
}

node {
    [Mailserver]
}

RESTClient ~~> [RequestLoggerMiddleware]
GraphQLClient ~~> [RequestLoggerMiddleware]

[RequestLoggerMiddleware] ~~> [AutoController]
[RequestLoggerMiddleware] ~~> [AutoResolver]

[AutoController] ..> [AutoService]
[AutoResolver] ..> [AutoService]
[AutoService] ..> [Repository<Auto>]

[Repository<Auto>] ~~> [TypeORM]
[TypeORM] ~~> [Tabelle auto]
[TypeORM] ~~> [Tabelle modell]
[TypeORM] ~~> [Tabelle bild]

[AutoController] ..> [nest-keycloak-connect]
[nest-keycloak-connect] ~~> [Keycloak]

[AutoService] ..> [MailService]
[MailService] ~~> [nodemailer]
[nodemailer] ~~> [Mailserver]

[MailService] ~[hidden]~> [nest-keycloak-connect]

footer Niklas Lisker

@enduml
