' Preview durch <Alt>d

@startuml Sequenzdiagramm

actor Gast

boundary AutoGetController
control AutoReadService
database auto

Gast -> AutoGetController : GET / getById()
AutoGetController -> AutoReadService: findById()
AutoReadService -> auto: [TypeORM]

footer Niklas Lisker

@enduml
